// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  module.exports = function(grunt) {
    require('load-grunt-tasks')(grunt);
    grunt.initConfig({
      shell: {
        test_all: {
          command: 'phpunit --config ../phpunit.xml.dist'
        },
        test_helpers: {
          command: 'phpunit --config ../phpunit.xml.dist --testsuite Helpers'
        },
        test_commands: {
          command: 'phpunit --config ../phpunit.xml.dist --testsuite Commands'
        },
        phpcs_commands: {
          command: 'phpcs -a --standard=PEAR  ../Test/Command/*.php'
        },
        phpcs_helpers: {
          command: 'phpcs --standard=PEAR  ../Test/Helper/*.php'
        }
      },
      watch: {
        scripts: {
          files: '../Test/Helper/*.php',
          tasks: ['shell:phpcs_helpers'],
          options: {
            spawn: false,
            event: ['all']
          }
        }
      }
    });
    return grunt.registerTask('default', ['shell']);
  };

}).call(this);
